steps:
  # Install gcloud beta components
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['components', 'install', 'beta']

  # Check Terraform version
  - name: 'hashicorp/terraform:1.7.0'
    args: ['version']

  # Format and validate Terraform code
  - name: 'hashicorp/terraform:1.7.0'
    args: ['fmt', '-check', '-recursive']
    dir: 'terraform'

  - name: 'hashicorp/terraform:1.7.0'
    args: ['validate']
    dir: 'terraform'

  # Initialize Terraform
  - name: 'hashicorp/terraform:1.7.0'
    args: ['init']
    dir: 'terraform'

  # Plan Terraform changes
  - name: 'hashicorp/terraform:1.7.0'
    args: ['plan', '-out=tfplan']
    dir: 'terraform'

  # Apply Terraform changes
  - name: 'hashicorp/terraform:1.7.0'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: 'terraform'

artifacts:
  objects:
    location: 'gs://${_PROJECT_ID}-terraform-plans/'
    paths: ['tfplan']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s' 