steps:
  # Initialize Terraform in the VM module directory
  - name: 'hashicorp/terraform:1.11.4'
    entrypoint: 'sh'
    args: 
      - '-c'
      - 'cd modules/vm && terraform init'

  # Plan the VM module changes
  - name: 'hashicorp/terraform:1.11.4'
    entrypoint: 'sh'
    args: 
      - '-c'
      - 'cd modules/vm && terraform plan -input=false -out=tfplan'

  # Apply the VM module changes
  - name: 'hashicorp/terraform:1.11.4'
    entrypoint: 'sh'
    args: 
      - '-c'
      - 'cd modules/vm && terraform apply -input=false tfplan'

options:
  logging: CLOUD_LOGGING_ONLY 