steps:
  # Combined Terraform Init & Plan with shared context
  - name: 'hashicorp/terraform:1.11.4'
    entrypoint: 'sh'
    args: 
      - '-c'
      - 'terraform init && terraform plan -input=false -out=tfplan'

options:
  logging: CLOUD_LOGGING_ONLY