steps:
  # Install Terraform and set up credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'activate-service-account', '--key-file=/workspace/terraform/soy-transducer-455914-i5-eb4acc5d0af2.json']

  # Run Terraform commands
  - name: 'hashicorp/terraform:1.7.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform version
        terraform fmt -check -recursive
        terraform validate
        terraform init -backend-config="bucket=gcp-doe-iac-state" -backend-config="prefix=terraform/state"
        terraform plan -out=tfplan

  # Store the plan as an artifact
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'terraform/tfplan', 'gs://gcp-doe-iac-state/terraform/plans/$${BUILD_ID}-plan']

artifacts:
  objects:
    location: 'gs://gcp-doe-iac-state/terraform/plans/'
    paths: ['terraform/tfplan']

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY 